### ISSUE TITLE
User Class: Test

### ISSUE THREAD

**Issue by AshleeAWebb** [AshleeAWebb/fitlit#6]
- [x] Check if it is an instance of the User
- [ ] Check for undefined on all methods that retrieve data
- [x] Check if it stores ID, Name, Address, Email, Stride, Daily Step Goal, and Friends(Own individual test)
- [x] Check the method to determine the average step goals of all users
- [x] Check the method to determine the first name
- [x] Check the method to get names of friends' names
- [x] Check method that ensures that the user ID can call the User data

**Comment by Adam-Meza** [comment]
I decided against having a method that returns the user ID since it will be stored as a property and be accessed at any time.
